language: node_js
os: linux
dist: xenial
node_js:
  - 16
cache: npm
branches:
  only:
    - main
script:
  - hexo generate
deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: public